"""
test_bluetooth.py
=================
Tests for BLE tracking endpoints, RSSI smoothing, distance estimation,
coordinate estimation, coordinate smoothing, zone classification, hysteresis,
and the combined occupancy status integration.

Uses the shared session-scoped `app` fixture from conftest.py.
Pure-service tests (RSSI smoothing, distance, zone) do NOT need a DB or app.
"""

import math
from datetime import datetime, timedelta, timezone
from unittest.mock import patch

import pytest

from app.ble_service import (
    smooth_rssi,
    rssi_to_distance,
    estimate_position,
    estimate_zone,
    smooth_position,
    _get_coordinate_zone,
)
from app import ble_config
import app.ble_service as _svc


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _valid_reading(**overrides):
    base = {
        "message_type": "bluetooth_rssi",
        "scanner_id": "anchor-left",
        "tag_id": "ROOM-TAG-01",
        "rssi": -61,
        "tx_power": None,
    }
    base.update(overrides)
    return base


def _post(client, **overrides):
    return client.post("/api/bluetooth/readings", json=_valid_reading(**overrides))


def _ts_now():
    return datetime.now(timezone.utc).isoformat()


def _ts_future(secs=2.0):
    return (datetime.now(timezone.utc) + timedelta(seconds=secs)).isoformat()


# ===========================================================================
# POST /api/bluetooth/readings  — happy path
# ===========================================================================

def test_post_reading_valid(client):
    resp = _post(client)
    assert resp.status_code == 201
    data = resp.get_json()
    assert data["success"] is True
    assert data["data"]["tag_id"] == "ROOM-TAG-01"
    assert data["data"]["scanner_id"] == "anchor-left"
    assert data["data"]["rssi"] == -61


def test_post_reading_returns_server_timestamp(client):
    resp = _post(client)
    assert resp.status_code == 201
    received_at = resp.get_json()["data"]["received_at"]
    # Must be a valid ISO-8601 timestamp generated by the server
    dt = datetime.fromisoformat(received_at)
    now = datetime.now(timezone.utc)
    assert abs((now - dt.replace(tzinfo=timezone.utc)).total_seconds()) < 5


def test_post_reading_null_tx_power_accepted(client):
    resp = _post(client, tx_power=None)
    assert resp.status_code == 201


def test_post_reading_integer_tx_power_accepted(client):
    resp = _post(client, tx_power=-20)
    assert resp.status_code == 201


def test_post_reading_all_valid_scanner_ids(client):
    for scanner in ble_config.KNOWN_SCANNER_IDS:
        resp = _post(client, scanner_id=scanner)
        assert resp.status_code == 201


def test_post_reading_rssi_at_lower_limit(client):
    # -120 is the minimum allowed
    resp = _post(client, rssi=-120)
    assert resp.status_code == 201


def test_post_reading_rssi_at_upper_limit(client):
    # 0 is the maximum allowed
    resp = _post(client, rssi=0)
    assert resp.status_code == 201


def test_post_multiple_readings_stored(client):
    for rssi in [-55, -60, -65]:
        resp = _post(client, rssi=rssi)
        assert resp.status_code == 201


# ===========================================================================
# POST /api/bluetooth/readings  — validation failures
# ===========================================================================

def test_post_reading_missing_body(client):
    resp = client.post("/api/bluetooth/readings")
    assert resp.status_code == 400


def test_post_reading_non_json_content_type(client):
    resp = client.post("/api/bluetooth/readings", data="scanner_id=x")
    assert resp.status_code == 400


def test_post_reading_invalid_json(client):
    resp = client.post(
        "/api/bluetooth/readings", data="not json", content_type="application/json"
    )
    assert resp.status_code == 400


def test_post_reading_wrong_message_type(client):
    resp = _post(client, message_type="wrong_type")
    assert resp.status_code == 400


def test_post_reading_missing_message_type(client):
    payload = _valid_reading()
    del payload["message_type"]
    resp = client.post("/api/bluetooth/readings", json=payload)
    assert resp.status_code == 400


def test_post_reading_unknown_scanner(client):
    resp = _post(client, scanner_id="unknown-anchor")
    assert resp.status_code == 400
    assert "Unknown scanner_id" in resp.get_json()["error"]


def test_post_reading_empty_scanner_id(client):
    resp = _post(client, scanner_id="")
    assert resp.status_code == 400


def test_post_reading_invalid_tag_prefix(client):
    resp = _post(client, tag_id="OTHER-TAG-01")
    assert resp.status_code == 400
    assert "ROOM-TAG-" in resp.get_json()["error"]


def test_post_reading_empty_tag_id(client):
    resp = _post(client, tag_id="")
    assert resp.status_code == 400


def test_post_reading_rssi_above_zero(client):
    resp = _post(client, rssi=10)
    assert resp.status_code == 400


def test_post_reading_rssi_below_minus120(client):
    resp = _post(client, rssi=-121)
    assert resp.status_code == 400


def test_post_reading_rssi_as_string(client):
    resp = _post(client, rssi="-55")
    assert resp.status_code == 400


def test_post_reading_rssi_as_float(client):
    resp = _post(client, rssi=-55.5)
    assert resp.status_code == 400


def test_post_reading_rssi_as_boolean(client):
    resp = _post(client, rssi=True)
    assert resp.status_code == 400


def test_post_reading_tx_power_as_string(client):
    resp = _post(client, tx_power="high")
    assert resp.status_code == 400


def test_post_reading_tx_power_as_boolean(client):
    resp = _post(client, tx_power=True)
    assert resp.status_code == 400


def test_post_reading_unrelated_ble_device_rejected(client):
    """Device name not starting with ROOM-TAG- must be rejected."""
    resp = _post(client, tag_id="AppleWatch-01")
    assert resp.status_code == 400


# ===========================================================================
# GET /api/bluetooth/position/<tag_id>
# ===========================================================================

def test_get_position_unseen_tag_returns_200(client):
    resp = client.get("/api/bluetooth/position/ROOM-TAG-99")
    assert resp.status_code == 200


def test_get_position_unseen_tag_status_unseen(client):
    resp = client.get("/api/bluetooth/position/ROOM-TAG-99")
    data = resp.get_json()
    assert data["status"] in ("unseen", "inactive", "outside", "unknown")


def test_get_position_unseen_tag_has_required_fields(client):
    resp = client.get("/api/bluetooth/position/ROOM-TAG-99")
    data = resp.get_json()
    for field in ("tag_id", "status", "zone", "stable_zone", "position",
                  "strongest_scanner", "scanner_rssi", "estimated_distances"):
        assert field in data


def test_get_position_invalid_tag_id(client):
    resp = client.get("/api/bluetooth/position/NOT-A-VALID-TAG")
    assert resp.status_code == 400


def test_get_position_active_tag_after_readings(client):
    # Post three readings from all anchors to make tag visible
    for scanner, rssi in [("anchor-left", -55), ("anchor-right", -65), ("anchor-back", -70)]:
        _post(client, scanner_id=scanner, rssi=rssi)
    resp = client.get("/api/bluetooth/position/ROOM-TAG-01")
    assert resp.status_code == 200
    data = resp.get_json()
    assert data["tag_id"] == "ROOM-TAG-01"


def test_get_position_returns_scanner_rssi(client):
    _post(client, scanner_id="anchor-left", rssi=-55)
    _post(client, scanner_id="anchor-right", rssi=-65)
    resp = client.get("/api/bluetooth/position/ROOM-TAG-01")
    data = resp.get_json()
    assert isinstance(data["scanner_rssi"], dict)


# ===========================================================================
# GET /api/bluetooth/tags
# ===========================================================================

def test_get_tags_returns_200(client):
    resp = client.get("/api/bluetooth/tags")
    assert resp.status_code == 200


def test_get_tags_has_required_fields(client):
    resp = client.get("/api/bluetooth/tags")
    data = resp.get_json()
    assert "active_tag_count" in data
    assert "tags" in data
    assert isinstance(data["tags"], list)


def test_get_tags_empty_when_no_data(client):
    resp = client.get("/api/bluetooth/tags")
    data = resp.get_json()
    # No active tags expected if no recent readings
    assert data["active_tag_count"] >= 0


def test_get_tags_includes_active_tag(client):
    # Submit readings and check if tag appears
    for scanner in ["anchor-left", "anchor-right", "anchor-back"]:
        _post(client, scanner_id=scanner, rssi=-60)
    resp = client.get("/api/bluetooth/tags")
    data = resp.get_json()
    assert data["active_tag_count"] >= 1
    tag_ids = [t["tag_id"] for t in data["tags"]]
    assert "ROOM-TAG-01" in tag_ids


def test_get_tags_tag_has_required_fields(client):
    _post(client, scanner_id="anchor-left", rssi=-60)
    resp = client.get("/api/bluetooth/tags")
    data = resp.get_json()
    if data["tags"]:
        tag = data["tags"][0]
        for field in ("tag_id", "status", "stable_zone", "last_seen_at"):
            assert field in tag


# ===========================================================================
# Combined occupancy status integration
# ===========================================================================

def test_occupancy_status_includes_ble_fields(client):
    resp = client.get("/api/occupancy/status")
    assert resp.status_code == 200
    data = resp.get_json()
    assert "bluetooth_tag_count" in data
    assert "bluetooth_zones" in data
    assert "bluetooth_positions" in data


def test_occupancy_status_ble_tag_count_is_integer(client):
    resp = client.get("/api/occupancy/status")
    data = resp.get_json()
    assert isinstance(data["bluetooth_tag_count"], int)


def test_occupancy_status_ble_zones_has_expected_zones(client):
    resp = client.get("/api/occupancy/status")
    data = resp.get_json()
    zones = data["bluetooth_zones"]
    for expected_zone in ("left", "centre", "right", "back"):
        assert expected_zone in zones


def test_ble_tag_count_does_not_affect_pir_occupancy(client):
    # Submit BLE readings
    for scanner in ["anchor-left", "anchor-right", "anchor-back"]:
        _post(client, scanner_id=scanner, rssi=-60)

    resp = client.get("/api/occupancy/status")
    data = resp.get_json()
    # BLE presence must not alter the PIR occupancy count
    assert data["occupancy"] == 0


def test_existing_occupancy_fields_still_present(client):
    resp = client.get("/api/occupancy/status")
    data = resp.get_json()
    for field in ("occupancy", "status", "radar_presence", "radar_target_count"):
        assert field in data


# ===========================================================================
# RSSI Smoothing (pure service tests — no DB)
# ===========================================================================

def test_smooth_rssi_median_odd():
    readings = [
        {"scanner_id": "anchor-left", "rssi": -55},
        {"scanner_id": "anchor-left", "rssi": -57},
        {"scanner_id": "anchor-left", "rssi": -56},
    ]
    result = smooth_rssi(readings)
    assert result["anchor-left"] == -56


def test_smooth_rssi_median_even():
    readings = [
        {"scanner_id": "anchor-left", "rssi": -55},
        {"scanner_id": "anchor-left", "rssi": -57},
    ]
    result = smooth_rssi(readings)
    assert result["anchor-left"] == -56.0


def test_smooth_rssi_extreme_outlier_not_dominant():
    readings = [
        {"scanner_id": "anchor-left", "rssi": -55},
        {"scanner_id": "anchor-left", "rssi": -57},
        {"scanner_id": "anchor-left", "rssi": -56},
        {"scanner_id": "anchor-left", "rssi": -80},  # outlier
        {"scanner_id": "anchor-left", "rssi": -54},
    ]
    result = smooth_rssi(readings)
    # Median of sorted [-80, -57, -56, -55, -54] is -56
    assert result["anchor-left"] == -56


def test_smooth_rssi_multiple_anchors_separated():
    readings = [
        {"scanner_id": "anchor-left", "rssi": -50},
        {"scanner_id": "anchor-right", "rssi": -60},
        {"scanner_id": "anchor-left", "rssi": -52},
    ]
    result = smooth_rssi(readings)
    assert result["anchor-left"] == -51
    assert result["anchor-right"] == -60


def test_smooth_rssi_single_reading():
    readings = [{"scanner_id": "anchor-back", "rssi": -70}]
    result = smooth_rssi(readings)
    assert result["anchor-back"] == -70


def test_smooth_rssi_equal_readings():
    readings = [{"scanner_id": "anchor-left", "rssi": -60}] * 5
    result = smooth_rssi(readings)
    assert result["anchor-left"] == -60


def test_smooth_rssi_empty_returns_empty():
    assert smooth_rssi([]) == {}


# ===========================================================================
# RSSI-to-distance estimation (pure service tests)
# ===========================================================================

def test_distance_at_reference_equals_one_metre():
    # reference_rssi_at_1m = -50.0 for anchor-left
    dist = rssi_to_distance(-50.0, "anchor-left")
    assert abs(dist - 1.0) < 0.001


def test_distance_stronger_rssi_gives_shorter_distance():
    dist = rssi_to_distance(-40.0, "anchor-left")
    assert dist < 1.0


def test_distance_weaker_rssi_gives_longer_distance():
    dist = rssi_to_distance(-60.0, "anchor-left")
    assert dist > 1.0


def test_distance_invalid_anchor_returns_none():
    assert rssi_to_distance(-55.0, "unknown-anchor") is None


def test_distance_clamped_to_configured_max():
    max_d = ble_config.BLE_SETTINGS["max_distance_metres"]
    dist = rssi_to_distance(-120.0, "anchor-left")
    assert dist == max_d


def test_distance_positive():
    dist = rssi_to_distance(-65.0, "anchor-right")
    assert dist > 0


def test_distance_uses_per_anchor_calibration():
    # anchor-left ref=-50.0, anchor-back ref=-49.0
    d_left = rssi_to_distance(-50.0, "anchor-left")
    d_back = rssi_to_distance(-49.0, "anchor-back")
    # Both at their own reference RSSI → both should be 1.0 m
    assert abs(d_left - 1.0) < 0.001
    assert abs(d_back - 1.0) < 0.001


# ===========================================================================
# Coordinate estimation (pure service tests)
# ===========================================================================

def test_estimate_position_three_anchors_returns_result():
    distances = {"anchor-left": 1.0, "anchor-right": 5.0, "anchor-back": 4.0}
    pos = estimate_position(distances)
    assert pos is not None
    assert pos["method"] == "weighted_centroid"


def test_estimate_position_closer_to_nearest_anchor():
    distances = {"anchor-left": 1.0, "anchor-right": 5.0, "anchor-back": 4.0}
    pos = estimate_position(distances)
    # anchor-left is at (0,0) and closest; result should be in left half
    assert pos["x"] < 3.0


def test_estimate_position_two_anchors_equal_distance_is_midpoint():
    # anchor-left (0,0) and anchor-right (6,0) at equal distance → centroid (3,0)
    distances = {"anchor-left": 1.0, "anchor-right": 1.0}
    pos = estimate_position(distances)
    assert pos is not None
    assert pos["x"] == 3.0
    assert pos["y"] == 0.0


def test_estimate_position_insufficient_anchors_returns_none():
    pos = estimate_position({"anchor-left": 1.0})
    assert pos is None


def test_estimate_position_no_anchors_returns_none():
    assert estimate_position({}) is None


def test_estimate_position_x_clamped_to_room():
    # Artificially pull anchor-left far outside room
    with patch.dict("app.ble_config.ANCHOR_POSITIONS",
                    {"anchor-left": {"x": -50.0, "y": -50.0, "zone": "left"}}):
        distances = {"anchor-left": 0.1, "anchor-right": 20.0, "anchor-back": 20.0}
        pos = estimate_position(distances)
    assert pos["x"] >= 0.0
    assert pos["y"] >= 0.0


def test_estimate_position_y_within_room():
    distances = {"anchor-left": 1.0, "anchor-right": 1.0, "anchor-back": 1.0}
    pos = estimate_position(distances)
    assert 0.0 <= pos["y"] <= ble_config.ROOM_DIMENSIONS["height"]


def test_estimate_position_returns_quality_field():
    distances = {"anchor-left": 1.0, "anchor-right": 5.0, "anchor-back": 4.0}
    pos = estimate_position(distances)
    assert "quality" in pos
    assert 0.0 <= pos["quality"] <= 1.0


def test_estimate_position_returns_label_experimental():
    distances = {"anchor-left": 1.0, "anchor-right": 5.0, "anchor-back": 4.0}
    pos = estimate_position(distances)
    assert pos["label"] == "experimental"


def test_estimate_position_returns_unit_metres():
    distances = {"anchor-left": 1.0, "anchor-right": 5.0, "anchor-back": 4.0}
    pos = estimate_position(distances)
    assert pos["unit"] == "metres"


# ===========================================================================
# Coordinate smoothing (pure service tests)
# ===========================================================================

def test_smooth_position_first_call_returns_raw(monkeypatch):
    monkeypatch.setattr(_svc, "_tag_state", {})
    raw = {"x": 2.5, "y": 1.5, "unit": "metres", "method": "test", "label": "experimental", "quality": 1.0}
    result = smooth_position("ROOM-TAG-EMA", raw)
    assert result["x"] == 2.5
    assert result["y"] == 1.5


def test_smooth_position_ema_reduces_jump(monkeypatch):
    monkeypatch.setattr(_svc, "_tag_state", {})
    alpha = ble_config.BLE_SETTINGS["position_ema_alpha"]
    base = {"unit": "metres", "method": "test", "label": "experimental", "quality": 1.0}

    smooth_position("ROOM-TAG-EMA", {**base, "x": 0.0, "y": 0.0})
    result = smooth_position("ROOM-TAG-EMA", {**base, "x": 10.0, "y": 10.0})

    expected = alpha * 10.0  # prev=0, new=10, alpha blended
    assert abs(result["x"] - round(expected, 2)) < 0.001


def test_smooth_position_does_not_jump_across_room(monkeypatch):
    monkeypatch.setattr(_svc, "_tag_state", {})
    base = {"unit": "metres", "method": "test", "label": "experimental", "quality": 1.0}

    for x in [1.0, 1.1, 1.0, 1.1]:
        prev = smooth_position("ROOM-TAG-EMA", {**base, "x": x, "y": 0.0})

    # Now jump to other side of room
    result = smooth_position("ROOM-TAG-EMA", {**base, "x": 6.0, "y": 5.0})
    # EMA should still be closer to 1.x, not 6.0
    assert result["x"] < 4.0


def test_smooth_position_none_input_returns_none(monkeypatch):
    monkeypatch.setattr(_svc, "_tag_state", {})
    assert smooth_position("ROOM-TAG-EMA", None) is None


# ===========================================================================
# Zone mapping (pure service tests)
# ===========================================================================

def test_coordinate_zone_left():
    pos = {"x": 1.0, "y": 2.5}
    assert _get_coordinate_zone(pos) == "left"


def test_coordinate_zone_right():
    pos = {"x": 5.0, "y": 2.5}
    assert _get_coordinate_zone(pos) == "right"


def test_coordinate_zone_back():
    pos = {"x": 3.0, "y": 4.5}
    assert _get_coordinate_zone(pos) == "back"


def test_coordinate_zone_centre():
    pos = {"x": 3.0, "y": 1.5}
    assert _get_coordinate_zone(pos) == "centre"


def test_coordinate_zone_none_returns_none():
    assert _get_coordinate_zone(None) is None


# ===========================================================================
# Stable Zone estimation + hysteresis (pure service tests)
# ===========================================================================

def test_estimate_zone_unknown_initially(monkeypatch):
    monkeypatch.setattr(_svc, "_tag_state", {})
    rssi = {"anchor-left": -50}
    zone = estimate_zone("TAG-Z1", rssi, None, _ts_now())
    assert zone == "unknown"


def test_estimate_zone_centre_when_two_anchors_close(monkeypatch):
    """Two anchors within threshold → candidate = centre; after hold_seconds it becomes stable."""
    monkeypatch.setattr(_svc, "_tag_state", {})
    threshold = ble_config.BLE_SETTINGS["centre_rssi_threshold_db"]
    rssi = {"anchor-left": -50, "anchor-right": -50 - threshold + 1}  # diff < threshold

    t1 = _ts_now()
    # First call: establishes candidate
    estimate_zone("TAG-Z2", rssi, None, t1)
    # Call again after hold time
    t2 = _ts_future(ble_config.BLE_SETTINGS["zone_hold_seconds"] + 0.1)
    zone = estimate_zone("TAG-Z2", rssi, None, t2)
    assert zone == "centre"


def test_estimate_zone_hysteresis_prevents_rapid_flap(monkeypatch):
    """Zone should not flip every single reading; old zone is retained until hold time elapsed."""
    monkeypatch.setattr(_svc, "_tag_state", {})
    hold = ble_config.BLE_SETTINGS["zone_hold_seconds"]

    rssi_left = {"anchor-left": -45, "anchor-right": -75, "anchor-back": -75}
    rssi_right = {"anchor-right": -45, "anchor-left": -75, "anchor-back": -75}

    t = _ts_now()
    # Stabilise in "left" zone (need to get past hold time)
    estimate_zone("TAG-Z3", rssi_left, None, t)
    t_stable = _ts_future(hold + 0.5)
    stable = estimate_zone("TAG-Z3", rssi_left, None, t_stable)
    assert stable == "left"

    # Immediately flip to right readings — should NOT change yet
    zone_after_flip = estimate_zone("TAG-Z3", rssi_right, None, _ts_future(hold + 0.6))
    assert zone_after_flip == "left"  # hysteresis holds


def test_estimate_zone_transitions_after_hold_time(monkeypatch):
    monkeypatch.setattr(_svc, "_tag_state", {})
    hold = ble_config.BLE_SETTINGS["zone_hold_seconds"]

    rssi_left = {"anchor-left": -45, "anchor-right": -75, "anchor-back": -75}
    rssi_right = {"anchor-right": -45, "anchor-left": -75, "anchor-back": -75}

    t = _ts_now()
    estimate_zone("TAG-Z4", rssi_left, None, t)
    estimate_zone("TAG-Z4", rssi_left, None, _ts_future(hold + 0.1))

    # Now move to right zone consistently for longer than hold time
    t_right_start = _ts_future(hold + 0.2)
    estimate_zone("TAG-Z4", rssi_right, None, t_right_start)
    t_right_done = (
        datetime.now(timezone.utc) + timedelta(seconds=hold * 2 + 1.0)
    ).isoformat()
    final_zone = estimate_zone("TAG-Z4", rssi_right, None, t_right_done)
    assert final_zone == "right"


def test_estimate_zone_empty_rssi_returns_unknown(monkeypatch):
    monkeypatch.setattr(_svc, "_tag_state", {})
    zone = estimate_zone("TAG-Z5", {}, None, _ts_now())
    assert zone == "unknown"
